# Generated by Django 3.0.3 on 2020-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='Enter due date , format - mm/dd/yy '),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, choices=[('p', 'Personal'), ('w', 'Work'), ('s', 'Shopping'), ('o', 'Others')], default='p', help_text='Task Label', max_length=1),
        ),
    ]
