# Generated by Django 3.0.3 on 2020-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200607_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='Enter due date , format - mm/dd/yyyy '),
        ),
    ]
